baseurl         = "https://reuse.fsfe.org/"
languageCode    = "en-us"
title           = "REUSE"
theme           = "sp-minimal"
disqusShortname = ""
paginate        = 5

[params]
  title       = "REUSE
  subtitle    = "Developer best practices for expressing license and copyright information in Free and Open Source Software projects"
  authorImage = "r.png"
  orgurl      = "https://fsfe.org/"
  description = "Best practices on adding license information in ways which not only humans can read, but computers as well. Machine readable copyright and license information, simply put!"

  #"single" or "single"
  renderType = "single"
  #"simple" or "original"
  themeStyle = "simple"

  googleAnalytics = ""

  name = "FSFE e.V."
  pageNotFoundTitle = "404 - Page not found"

